### ISSUE TITLE
代码有错误，数据库文件没有数据，能否提供一个，谢谢

### ISSUE THREAD

**Issue by itshu** [remix7/cwechat#1]

**Comment by remix7** [comment]
只是数据库结构 代码错误能否贴出来呢？

________________________________
发件人: itshu <notifications@github.com>
发送时间: 2017年1月4日 19:37
收件人: remix7/cwechat
抄送: Subscribed
主题: [remix7/cwechat] 代码有错误，数据库文件没有数据，能否提供一个，谢谢 (#1)


―

**Comment by itshu** [comment]
service里少两个方法，直接编译的时候就报错。你可以放到ide里看一下
添加上了 你從新pull一下 應該是可以的

**Comment by remix7** [comment]
@itshu 添加上了

**Comment by remix7** [comment]
[cid:c15f9282-ac78-4531-883a-985355e5cf4c]

方法和页面已经添加了 请pull查看

________________________________
发件人: itshu <notifications@github.com>
发送时间: 2017年1月6日 13:58
收件人: remix7/cwechat
抄送: liutao; Comment
主题: Re: [remix7/cwechat] 代码有错误，数据库文件没有数据，能否提供一个，谢谢 (#1)


service里少两个方法，直接编译的时候就报错。你可以放到ide里看一下

―

**Comment by itshu** [comment]
@remix7 这次错误更多了，编译错误，少方法

**Comment by remix7** [comment]
@itshu 你把错误贴出来  在我这一切正常

**Comment by itshu** [comment]
CwechatController.java  127行 cwechatAccess.getOriginalId()  没有这个方法，
ReceiveWechatMessageServiceImpl.java   46行 没有 findAllByToUserName 方法

**Comment by remix7** [comment]
@itshu 好了 你再更新一下看

**Comment by itshu** [comment]
多谢，没用户咋登陆呢

**Comment by remix7** [comment]
@itshu 这正是你要摸索的地方
